openapi: 3.0.0
info:
  title: Kreditkartenkonto API
  version: 1.0.0
paths:
  /kreditkartenkonto:
    get:
      summary: "Get a list of Kreditkartenkonten"
      parameters:
        - name: max
          in: query
          description: "Maximale Anzahl der Ergebnisse"
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
      responses:
        '200':
          description: "Erfolgreiche Antwort"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Kreditkartenkonto'
    post:
      summary: "Create a new Kreditkartenkonto"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Kreditkartenkonto'
      responses:
        '201':
          description: "Kreditkartenkonto erfolgreich erstellt"
        '400':
          description: "Validation Error"
  /kreditkartenkonto/{id}:
    get:
      summary: "Get a specific Kreditkartenkonto"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Erfolgreiche Antwort"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kreditkartenkonto'
        '404':
          description: "Kreditkartenkonto nicht gefunden"
    put:
      summary: "Update a specific Kreditkartenkonto"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Kreditkartenkonto'
      responses:
        '200':
          description: "Kreditkartenkonto erfolgreich aktualisiert"
        '400':
          description: "Validation Error"
        '404':
          description: "Kreditkartenkonto nicht gefunden"
    delete:
      summary: "Delete a specific Kreditkartenkonto"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: "Kreditkartenkonto erfolgreich gelöscht"
        '404':
          description: "Kreditkartenkonto nicht gefunden"
components:
  schemas:
    Kreditkartenkonto:
      type: object
      properties:
        id:
          type: integer
        kontoName:
          type: string
        saldo:
          type: number
          format: float
        waehrung:
          type: string
